---
- name: install extra packages
  package:
    name:
      - java-11-openjdk-devel
      - maven
    state: present

- name: create backend directory
  file:
    path: "{{ backend_root }}/{{ backend_name }}/config"
    state: directory
    mode: 0755
    owner: root
    group: root
    recurse: yes

- name: copy backend configuration
  template:
    src: ../templates/application.yml.j2
    dest: "{{ backend_root}}/{{ backend_name }}/config/application.yml"
    owner: root
    group: root
    mode: 0644

- name: checkout backend repo
  git:
    dest: "{{ backend_checkout_dir }}"
    repo: "{{ backend_repo }}"
    version: main
    key_file: /root/.ssh/id_rsa

- name: Building backend
  include: run_shell.yml
  vars:
    name: Building backend
    command: cd {{ backend_checkout_dir }} && mvn clean install
    ignore_errors: no

- name: copy backend app
  copy:
    src: "{{ backend_checkout_dir }}/target/{{ backend_name }}.jar"
    dest: "{{ backend_root}}/{{ backend_name }}/{{ backend_name }}.jar"
    owner: root
    group: root
    mode: 0755
    remote_src: yes
  notify:
    - restart_backend

- name: remove backend repo directory
  file:
    path: "{{ backend_checkout_dir }}"
    state: absent

- name: copy backend service
  template:
    src: ../templates/backend.service.j2
    dest: "/etc/systemd/system/{{ backend_name }}.service"
    owner: root
    group: root
    mode: 0644

- name: start service {{ backend_name }}
  service:
    name: "{{ backend_name }}"
    state: started
    enabled: true
...