---
- name: setup motd
  template:
    src: ../templates/motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644

- name: install packages
  package:
    name:
      - git
      - logrotate
    state: present
...
